### ISSUE TITLE
EPOE breaks parsing?

### ISSUE THREAD

**Issue by OHQSaucey** [Metastruct/EPOE#1]
I recently put an anti cheat program on my server and epoe just stopped working after that. I was told by the Developer of the AC that EPOE "breaks the parsing" and I was wondering if there is a way to fix this.

The AC tells me that I try to run these commands below.
STEAM_0:1:19526842 tried running command: +epoe 2
STEAM_0:1:19526842 tried running command: -epoe 2

I think it may be due to the space or possibly even the + that could be causing the issue for it not to work. EPOE shows up on my server, it just doesn't show any information in it.

**Comment by Python1320** [comment]
I need to know what parsing he's talking about to be able to fix it.

**Comment by OHQSaucey** [comment]
He lives over in Germany, so I do not think I could get a hold of him right this minute. I would want to say it has something to do with "+epoe 2" but I could be wrong. When I try to login it doesn't say anything, and when I try to logout it says I am not subscribed. Something is not letting me login to EPOE if that helps at all.

**Comment by Noiwex** [comment]
Don't use placebo anticheats.
