### ISSUE TITLE
Dammit python

### ISSUE THREAD

**Issue by ghost** [Metastruct/EPOE#2]
EPOE shows everyone who join's's's's ip address :l

**Comment by notcake** [comment]
DEAL WITH IT ![:B1:](https://steamcommunity-a.akamaihd.net/economy/emoticon/B1)

**Comment by notcake** [comment]
regular players aren't supposed to be subscribed to the epoe stream anyway

**Comment by danielga** [comment]
I believe you wanted this.
![:B1:](https://steamcommunity-a.akamaihd.net/economy/emoticon/B1)

**Comment by PotcFdk** [comment]
> regular players aren't supposed to be subscribed to the epoe stream anyway

this
