### ISSUE TITLE
E2 printTable(Array) prints to EPOE

### ISSUE THREAD

**Issue by ghost** [Metastruct/EPOE#5]
I had no idea this would happen, I made something in E2 to make an array add strings to itself constantly and print them to ME, but somehow it ended up on flex's spyware EPOE and now I am banned.
Please fix this or fix flex. :3

**Comment by Cynosphere** [comment]
please no personal attacks, thanks

**Comment by Noiwex** [comment]
I don't see personal attacks here. Either way I'll investigate this, but this is probably solely one-server problem.
